const { test, expect } = require('@playwright/test');
const appFunctions = require('../functions')
const {deploy_url} = require('../urls')
const selectors = require('../selectors')
const path = require('path');

test('Embassy Visa', async({page}) => {
    test.slow()
    await page.goto(deploy_url + 'australia/apply-now')
    await appFunctions.autofillExisting(page, "australia/apply-now/edit-traveler/0")
    await page.waitForURL("**/australia/apply-now/traveler-review")
    const continue_sidebar = page.getByRole("button").getByText("Continue")
    await continue_sidebar.click()
    await page.waitForURL("**/australia/apply-now/contact-details")
    await continue_sidebar.click() 
    await appFunctions.newPaymentCheckout(page, '6011 1111 1111 1117', '123')
    const payment_btn = page.locator('id=btnSubmitPayment')
    await expect(payment_btn).toBeVisible()
    await expect(payment_btn).toBeEnabled()
    await payment_btn.click()

    await page.waitForNavigation({waitUntil: 'load'})
    await page.getByTestId("transition-page-button").click()
    let Order_num = page.url().split("/")[4] 
    await page.getByPlaceholder('111-222-3333').fill('11111111')
    await page.getByTestId('option-WhatsApp').click()
    await page.waitForTimeout(2000)
    await selectors.booleanOptions(page, "general.traveling_with_others", "option-No")
    await selectors.booleanOptions(page, "general.need_multiple_entry_visa", "option-No")
    await selectors.dropdownOptions(page, "dropdown-general.travel_reason", "Tourism")
    await page.waitForTimeout(1000)
    await page.getByTestId("option-Me").click()
    await page.waitForTimeout(1000)
    const next_btn = page.locator('id=btnContinueUnderSection')
    await page.waitForTimeout(1000)
    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=travel_general")
    await selectors.arrival_date(page)
    await selectors.departure_date(page, "general.departure_date")

    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_appointment_selection")
    await page.locator('[name="applicant.0.home_country"]').click()
    await page.waitForTimeout(2000)
    await page.getByTestId("dropdown-applicant.0.home_country").fill("mexico")
    await page.getByRole('option', { name: 'Mexico flag Mexico' }).click()
    await page.waitForTimeout(2000)
    const location_1 = page.locator('[name="applicant.0.appointment_location_id"]')
    await location_1.getByTestId('option-4575').click()
    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_personal")
    await page.waitForTimeout(3000)
    await selectors.dropdownSelector(page, "applicant.0.occupation_triage", "dropdown-applicant.0.occupation_triage", "Homemaker", "Homemaker (Partner-dependent income)")
    await selectors.dropdownOptions(page, "dropdown-applicant.0.income_triage", "Over 2500 USD monthly")
    await selectors.booleanOptions(page, "applicant.0.own_state_triage", "option-Yes")

    const other_countries_travel = page.getByTestId("option-Yes, in the last 5 years, I have traveled or have a visa for at least 1 of these countries - USA, Canada, Australia, UK, all Schengen countries.")
    await other_countries_travel.click()
    const visa_denied = page.getByTestId("option-I was denied this visa over 12 months ago")
    await visa_denied.click()
    await page.locator('[name="applicant.0.birth_city"]').fill("test")
    await selectors.addressApi(page, "applicant.0.home_address")
    await page.waitForTimeout(1000)
    await selectors.dropdownSelector(page, "applicant.0.secondary_document_issued_country", "dropdown-applicant.0.secondary_document_issued_country", "Mexico", "Mexico flag Mexico")
    await page.getByTestId('option-Male').click()
    await page.locator('[name="applicant.0.birth_city"]').fill("test")
    await page.waitForTimeout(1000)
    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_work")
    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_family")
    await page.waitForTimeout(2000)
    await selectors.dropdownOptions(page, "dropdown-applicant.0.marital_status", "Single / Never Married")
    await selectors.booleanOptions(page, "applicant.0.family_residents", "option-No")
    await selectors.booleanOptions(page, "applicant.0.family_traveling_with", "option-Yes")
    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_travel")
    await page.waitForTimeout(2000) 
    await page.locator('[name="amount"]').click()
    await page.waitForTimeout(1000)
    await page.keyboard.type("1234565", {delay: 100})
    await page.waitForTimeout(1000)
    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_past_travel")
    await selectors.booleanOptions(page ,"applicant.0.previously_visited", "option-No")
    await selectors.booleanOptions(page ,"applicant.0.current_visas", "option-No")
    await selectors.booleanOptions(page ,"applicant.0.refused_visa", "option-No")
    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_declarations")

    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_documents")

    await page.locator('id=instructions-continue').click()
    await page.locator('input[type="file"]').nth(1).setInputFiles(path.join(__dirname, 'uploads_passport/Applicant-Photo.jpg'))
    await page.waitForTimeout(8000)
    await page.locator('id=add-file-multiple-continue').click()

    await page.locator('id=instructions-continue').click()
    await page.locator('input[type="file"]').nth(1).setInputFiles(path.join(__dirname, 'uploads_passport/Applicant-Photo.jpg'))
    await page.waitForTimeout(8000)
    await page.locator('id=add-file-multiple-continue').click()

    await page.locator('id=instructions-continue').click()
    await page.locator('id=add-file-multiple-continue').click()
    
    await page.locator('id=instructions-continue').click()
    await page.locator('id=add-file-multiple-continue').click()

    await page.locator('id=instructions-continue').click()
    await page.locator('id=add-file-multiple-continue').click()
    
    await page.locator('id=instructions-continue').click()
    await page.getByTestId("try-another-way-button").click()
    await page.setInputFiles('input[type="file"]', path.join(__dirname, 'uploads_passport/passport.jpg'));
    await page.waitForTimeout(8000)
    await page.locator('id=review-continue').click()

    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_ocr_review")
    await page.waitForTimeout(3000)
    await page.getByText("Use selected details").click()
    await selectors.datePicker(page, "applicant.0.passport_issued_date", "13", "7", "2022")
    await selectors.booleanOptions(page, "applicant.0.other_document", "option-No")
    
    const submit_post_payment = page.locator('id=btnSubmitApplication')
    await expect(submit_post_payment).toBeEnabled()
    await submit_post_payment.click()
    await page.waitForNavigation({waitUntil: 'load'})
  })
  