const { test, expect } = require('@playwright/test');
const appFunctions = require('../functions')
const {deploy_url} = require('../urls')
const selectors = require('../selectors')
const path = require('path');

test('Embassy Visa', async({page}) => {
    test.slow()
    await page.goto(deploy_url + 'australia/apply-now')
    await appFunctions.autofillExisting(page, "australia/apply-now/edit-traveler/0")
    await page.waitForURL("**/australia/apply-now/traveler-review**")
    const continue_sidebar = page.getByRole("button").getByText("Continue")
    await continue_sidebar.click()
    await page.waitForURL("**/australia/apply-now/contact-details")
    await continue_sidebar.click() 
    await appFunctions.newPaymentCheckout(page, '6011 1111 1111 1117', '123')
    const payment_btn = page.locator('id=btnSubmitPayment')
    await expect(payment_btn).toBeVisible()
    await expect(payment_btn).toBeEnabled()
    await payment_btn.click()

    await page.waitForNavigation({waitUntil: 'load'})
    await page.getByText("Payment received").waitFor({state: 'visible'})
    let Order_num = page.url().split("/")[4] 
    const next_btn = page.locator('id=btnContinueUnderSection')
    await page.waitForTimeout(1000)
    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=travel_general")
    await selectors.arrival_date(page)
    await selectors.departure_date(page, "general.departure_date")
    await page.waitForTimeout(2000)
    await selectors.booleanOptions(page, "general.traveling_with_others", "option-No")
    await selectors.booleanOptions(page, "general.need_multiple_entry_visa", "option-No")
    await expect(next_btn).toBeEnabled()
    await next_btn.click()

    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_personal")
    await page.waitForTimeout(3000)
    await selectors.dropdownSelector(page, "applicant.0.birth_country", "dropdown-applicant.0.birth_country", "mexico", "MX")
    await page.locator('[name="applicant.0.birth_city"]').fill("test")
    await page.locator('[name="applicant.0.state_of_birth"]').fill("test")
    await selectors.dropdownOptions(page, "dropdown-applicant.0.marital_status", "Single / Never Married")
    await page.waitForTimeout(1000)
    await expect(next_btn).toBeEnabled()
    await next_btn.click()

    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_financial_support")
    await page.waitForTimeout(2000) 
    await page.locator('[name="amount"]').click()
    await page.waitForTimeout(1000)
    await page.keyboard.type("1234565", {delay: 100})
    await page.waitForTimeout(1000)
    await expect(next_btn).toBeEnabled()
    await next_btn.click()

    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_residency_information_after_payment")
    await page.waitForTimeout(2000) 
    await selectors.dropdownOptions(page, "dropdown-applicant.0.immigration_status", "Citizen")
    await expect(next_btn).toBeEnabled()
    await next_btn.click()

    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_work")
    await page.waitForTimeout(2000) 
    await selectors.dropdownOptions(page, "dropdown-applicant.0.occupation_triage", "Retired")
    await selectors.datePicker(page, "applicant.0.last_work_activity_date", "15", "12", "2020")
    await page.waitForTimeout(2000) 
    await expect(next_btn).toBeEnabled()
    await next_btn.click()

    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_travel")
    await selectors.booleanOptions(page, "applicant.0.relatives_in_destination", "option-No")
    await page.waitForTimeout(2000) 
    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_past_travel")
    await selectors.booleanOptions(page ,"applicant.0.applied_visa_triage", "option-No")
    await selectors.booleanOptions(page ,"applicant.0.current_visas", "option-No")
    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_declarations")

    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_documents")

    await page.locator('id=instructions-continue').click()
    await page.locator('input[type="file"]').nth(1).setInputFiles(path.join(__dirname, 'uploads_passport/Applicant-Photo.jpg'))
    await page.getByTestId("thumbnailPreview").waitFor({state: 'attached'})
    await page.locator('input[type="file"]').nth(1).setInputFiles(path.join(__dirname, 'uploads_passport/Applicant-Photo.jpg'))
    await page.waitForTimeout(8000)
    await page.locator('id=add-file-multiple-continue').click()

    await page.locator('id=instructions-continue').click()
    await page.locator('input[type="file"]').nth(1).setInputFiles(path.join(__dirname, 'uploads_passport/Applicant-Photo.jpg'))
    await page.getByTestId("thumbnailPreview").waitFor({state: 'attached'})
    await page.locator('id=add-file-multiple-continue').click()

    await page.locator('id=instructions-continue').click()
    await page.locator('id=add-file-multiple-continue').click()
    
    await page.locator('id=instructions-continue').click()
    await page.locator('id=add-file-multiple-continue').click()

    await page.locator('id=instructions-continue').click()
    await page.locator('id=add-file-multiple-continue').click()
    
    await page.locator('id=instructions-continue').click()
    await page.getByTestId("try-another-way-button").click()
    await page.setInputFiles('input[type="file"]', path.join(__dirname, 'uploads_passport/passport.jpg'));
    await page.locator("id=document-loading").waitFor({state: 'visible'})
    await page.locator("id=document-loading").waitFor({state: 'hidden', timeout: 15000})
    await page.locator('id=review-continue').click()

    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_ocr_review")
    await page.waitForTimeout(3000)
    await page.getByText("Use selected details").click()
    await selectors.datePicker(page, "applicant.0.passport_issued_date", "13", "7", "2022")
    await expect(next_btn).toBeEnabled()
    await next_btn.click()
    await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=contact_and_updates")
    await selectors.phoneNumber(page)
    const submit_post_payment = page.locator('id=btnSubmitApplication')
    await expect(submit_post_payment).toBeEnabled()
    await submit_post_payment.click()
    await page.waitForNavigation({waitUntil: 'load'})
  })
  