const { test, expect } = require('@playwright/test');
const appFunctions = require('../../functions');
const selectors = require('../../selectors')
const { deploy_url } = require('../../urls');

let Order_num

test('Kenya Eta', async ({ page }) => {
  test.slow()
  await page.goto(deploy_url + 'kenya/apply-now')
  await appFunctions.autofillExisting(page, "kenya/apply-now/edit-traveler/0")
  await page.waitForURL("**/kenya/apply-now/traveler-review")
  const continue_sidebar = page.getByRole("button").getByText("Continue")
  await continue_sidebar.click()
  await page.waitForURL("**/kenya/apply-now/contact-details")
  await continue_sidebar.click() 
  await appFunctions.newPaymentCheckout(page, '6011 1111 1111 1117', '123')
  const payment_btn = page.locator('id=btnSubmitPayment')
  await expect(payment_btn).toBeVisible()
  await expect(payment_btn).toBeEnabled()
  await payment_btn.click()
  
  await page.waitForNavigation({waitUntil: 'load'})
  await page.getByTestId("transition-page-button").click()
  
  await selectors.phoneNumber(page)
  Order_num = page.url().split("/")[4] 
  const next_btn = page.locator('id=btnContinueUnderSection')
  await page.waitForTimeout(1000)
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=travel_general")
  await page.waitForTimeout(2000)
  await selectors.arrival_date(page)
  await page.waitForTimeout(2000)
  await selectors.departure_date(page, "general.departure_date")
  await selectors.booleanOptions(page, "general.mode_of_transport", "option-Land")
  await selectors.dropdownSelector(page, "general.arrival_city", "dropdown-general.arrival_city", "kwale","Lungalunga Border - Kwale")
  await selectors.booleanOptions(page, "general.departure_mode_transport", "option-Land")
  await selectors.dropdownSelector(page, "general.departure_city", "dropdown-general.departure_city", "kwale","Lungalunga Border - Kwale")

  await page.waitForTimeout(2000)
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=accommodation")
  await page.waitForTimeout(2000)
  await selectors.inputText(page, "general.destination_location_name", 'Test')
  await page.waitForTimeout(2000)
  await selectors.inputText(page, "general.destination_state", 'Test')
  await page.waitForTimeout(2000)
  await selectors.inputText(page, "general.destination_address", 'Test')
  await page.waitForTimeout(2000)
  await selectors.inputText(page, "general.destination_city", 'Test')
  await page.waitForTimeout(2000)
  await selectors.inputText(page, "general.destination_zip", 'Test')
  await selectors.dropdownSelector(page, "general.destination_country", "dropdown-general.destination_country", "kenya", "KE")
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=emergency_contact")
  await page.waitForTimeout(2000)
  await selectors.inputText(page, "general.emergency_contact_name", "Test")
  await page.waitForTimeout(2000)
  await selectors.phoneWithDropdown(page, "general.emergency_contact_phone")
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_personal")
  await selectors.booleanOptions(page, "applicant.0.marital_status", "option-Single")
  await selectors.booleanOptions(page, "applicant.0.bahamas_disclaimer", "option-No")
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_work")
  await selectors.booleanOptions(page, "applicant.0.occupation", "option-Unemployed")
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_travel")
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_documents")
  await selectors.applicantPhoto(page)
  await selectors.passportPhoto(page)
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue/#step=trav0_ocr_review")
  await page.waitForTimeout(4000)
  const passportPostPaymentModal = await page.getByText("Use selected details").isVisible()
  if (passportPostPaymentModal){
    await page.getByText("Use selected details").click()
  }
  const passport_issue_day = page.locator('[name="applicant.0.passport_expiration_date.day"]')
  await expect(passport_issue_day).toBeVisible()
  await passport_issue_day.selectOption('13')
  await page.waitForTimeout(1000)  
  const passport_issue_month = page.locator('[name="applicant.0.passport_expiration_date.month"]')
  await passport_issue_month.selectOption('7')
  await page.waitForTimeout(1000)
  const passport_issue_year = page.locator('[name="applicant.0.passport_expiration_date.year"]')
  await passport_issue_year.selectOption('2028')  
  await page.waitForTimeout(1000)
  await page.locator("id=btnSubmitApplication").click()
  await page.waitForURL(deploy_url + "order-received-page/" + Order_num)
  await page.waitForTimeout(4000)
  const skip_recomendation = await page.locator('id=skip-recommendation-button').isVisible()
  if(skip_recomendation){
    await page.locator('id=skip-recommendation-button').click()    
  }
  
  await page.locator('id=trackApplication').click()
  
  await page.waitForURL(deploy_url + "order/" + Order_num)
})