const { test, expect } = require('@playwright/test');
const appFunctions = require('../../functions');
const selectors = require('../../selectors')
const { deploy_url } = require('../../urls');

let Order_num

test.fixme('Saint Kitts and Nevis ETA ', async ({ page }) => {
  test.slow()
  await page.goto(deploy_url + 'saint-kitts-and-nevis/apply-now')
  await appFunctions.autofillExisting(page, "saint-kitts-and-nevis/apply-now/edit-traveler/0")
  await page.waitForURL("**/saint-kitts-and-nevis/apply-now/traveler-review")
  const continue_sidebar = page.getByRole("button").getByText("Continue")
  await continue_sidebar.click()
  await page.waitForURL("**/saint-kitts-and-nevis/apply-now/contact-details")
  await continue_sidebar.click() 
  await appFunctions.newPaymentCheckout(page, '6011 1111 1111 1117', '123')
  const payment_btn = page.locator('id=btnSubmitPayment')
  await expect(payment_btn).toBeVisible()
  await expect(payment_btn).toBeEnabled()
  await payment_btn.click()
  
  
  await page.waitForNavigation({waitUntil: 'load'})
  await page.getByTestId("transition-page-button").click()
  await selectors.phoneNumber(page)
  await selectors.arrival_date(page)
  Order_num = page.url().split("/")[4] 
  const next_btn = page.locator('id=btnContinueUnderSection')
  await page.waitForTimeout(1000)
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=travel_general")
  await page.waitForTimeout(2000)
  await selectors.booleanOptions(page, 'general.hotel_info_us', 'option-No')
  await page.waitForTimeout(2000)
  await expect(next_btn).toBeEnabled()
  await next_btn.click()

  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=emergency_contact")
  await selectors.booleanOptions(page, 'general.emergency_contact_us', 'option-No')
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_personal")
  await selectors.booleanOptions(page, 'applicant.0.gender', 'option-Male')
  await selectors.dropdownSelector(page, "applicant.0.home_country", "dropdown-applicant.0.home_country", "mexico", "MX")
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_residency_information_after_payment")
  await selectors.addressApi(page, 'applicant.0.home_address')
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_work")
  await page.waitForTimeout(2000)
  await selectors.booleanOptions(page, 'applicant.0.are_employed', 'option-Employed (including self-employed, freelancers, and business owners)')
  await selectors.inputText(page, 'applicant.0.employer_name', 'Test')
  await selectors.booleanOptions(page, 'applicant.0.employer_info_us', 'option-No')
  await page.waitForTimeout(2000)
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_family")
  await page.waitForTimeout(2000)
  await selectors.inputText(page, "applicant.0.fathers_first_name", "Test")
  await selectors.inputText(page, "applicant.0.fathers_last_name", "Test")
  await selectors.inputText(page, "applicant.0.mothers_first_name", "Test")
  await selectors.inputText(page, "applicant.0.mothers_last_name", "Test")
  await page.waitForTimeout(2000)
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_declarations")
  await selectors.booleanOptions(page, "applicant.0.declarations_us", "option-No")
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_documents")
  await selectors.applicantPhoto(page)
  await selectors.passportPhoto(page)
  await page.waitForURL(deploy_url + "order/" + Order_num + "/continue#step=trav0_ocr_review")
  await page.getByText("Use selected details").click()
  await selectors.datePicker(page, "applicant.0.passport_issued_date", '1', '9', '2013')
  await page.locator("id=btnSubmitApplication").click()
  await page.waitForURL(deploy_url + "order-received-page/" + Order_num)
  await page.waitForTimeout(4000)
  const skip_recomendation = await page.locator('id=skip-recommendation-button').isVisible()
  if(skip_recomendation){
    await page.locator('id=skip-recommendation-button').click()    
  }
  
  await page.locator('id=trackApplication').click()
  
  await page.waitForURL(deploy_url + "order/" + Order_num)
})